language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - python setup.py --quiet install
    - pip --quiet install coverage python-coveralls

script:
    - python setup.py --quiet test
    - massedit --expression='line.replace("Copyright", "foobarfoobar")' LICENSE.txt | grep --quiet 'foobarfoobar'

after_success:
    - coverage run --source massedit tests.py
    - coveralls
